### ISSUE TITLE
colors to dots

### ISSUE THREAD

**Issue by lpantano** [pkerpedjiev/rnaplot#1]
Hi,

this is awesome! i would like to use this in my HTML report, and i was wondering if you plan to add an option to color the dots according to some label that can be provide.

thanks a lot for this gem!

cheers

**Comment by pkerpedjiev** [comment]
Hey!

Thanks for the kind words. If you just want an RNA layout for an HTML report, I would recommend using the fornac container, which you can find here:

https://github.com/pkerpedjiev/fornac

In there, you'll find `exampes/colors.html`. This shows a very minimal example for using colors. If you want to see what type of color strings you can use, just take a look at the "colors" section here:

http://nibiru.tbi.univie.ac.at/forna/documentation.html

Hope that helps!

**Comment by lpantano** [comment]
oh! that would help, I didn't know I can embebed inside an html! thanks a lot! feel free to close!
